import { mkdir, cp, writeFile, readFile } from 'node:fs/promises';
import { personalInfo as me, projects, experience, education, skills } from './src/data.js';

import { icon } from './src/icons.js';
import { createHash } from 'node:crypto';

const assetVersion = createHash('sha256').update(await readFile(new URL('./public/styles.css', import.meta.url))).update(await readFile(new URL('./public/site.js', import.meta.url))).digest('hex').slice(0, 12);
const out = new URL('./dist/', import.meta.url);
await mkdir(out, { recursive: true });
await cp(new URL('./public/', import.meta.url), out, { recursive: true });
const esc = s => String(s).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const arrow = icon('arrow-up-right');
const slugs = ['ai-agent-framework', 'reposense', 'vocsynapse'];
const labels = ['AGENT ARCHITECTURE', 'CODEBASE INTELLIGENCE', 'CUSTOMER INTELLIGENCE'];
const order = [1, 0, 2];
const descriptions = [
  'A modular Python core that connects documents, tools, and conversations. Built from scratch to understand the system beneath the assistant.',
  'Making a codebase easier to understand. Hybrid search and an evidence-gathering agent turn scattered code into grounded answers.',
  'Less inbox noise. More actionable feedback. An orchestrated workflow connects customer messages to structured engineering issues.'
];
function head(title, description, base) { return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#111310"><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><title>${esc(title)}</title><link rel="icon" href="${base}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${base}styles.css?v=${assetVersion}"><script src="${base}site.js?v=${assetVersion}" defer></script></head><body><a class="skip" href="#main">Skip to content</a>`; }
function header(base = './', detail = false) { return `<header class="header wrap"><a class="brand" href="${base}" aria-label="Vraj Shah home">vraj<span>_</span><small>SHAH</small></a><button class="menu" data-menu aria-controls="navigation" aria-expanded="false">Menu <span aria-hidden="true">${icon('plus')}</span></button><nav id="navigation" aria-label="Main navigation"><a href="${detail ? base : ''}#work">Work</a><a href="${detail ? base : ''}#about">About</a><a href="${detail ? base : ''}#experience">Experience</a><a class="nav-contact" href="${detail ? base : ''}#contact">Let’s talk ${arrow}</a></nav></header>`; }
function footer(base = './') { return `<footer class="wrap footer"><a class="brand" href="${base}">vraj<span>_</span></a><span>© ${new Date().getFullYear()} Vraj Shah · Built with intention.</span><button class="motion" data-motion aria-pressed="true"><span data-motion-label>Motion on</span><span class="motion-indicator" aria-hidden="true"></span></button></footer></body></html>`; }
function art(i) {
  if (i === 1) return `<div class="project-art code-art" aria-hidden="true"><div class="art-top"><span>REPOSITORY / INDEXED</span><i></i></div><div class="code-lines"><span><b>01</b> class <em>Repository</em>:</span><span><b>02</b> &nbsp;def <em>understand</em>(self):</span><span class="highlight"><b>03</b> &nbsp;&nbsp;return evidence</span><span><b>04</b> &nbsp;</span></div><div class="art-status"><span class="tiny-dot"></span> CONTEXT FOUND <span>${icon('arrow-up-right')}</span></div></div>`;
  if (i === 0) return `<div class="project-art agent-art" aria-hidden="true"><div class="art-top"><span>MODULAR BY DESIGN</span><i></i></div><div class="agent-diagram"><span class="agent-chip">DOCUMENTS</span><span class="agent-chip">MEMORY</span><div class="agent-core">a<span>i</span><small>AGENT CORE</small></div><span class="agent-chip">TOOLS</span><span class="agent-chip">PROVIDERS</span></div><div class="art-status">ONE CORE. MANY POSSIBILITIES. <span>${icon('arrow-up-right')}</span></div></div>`;
  return `<div class="project-art voc-art" aria-hidden="true"><div class="art-top"><span>FROM NOISE TO SIGNAL</span><i></i></div><div class="message-stack"><div><span>${icon('turn-right')}</span> A customer has something to say.</div><div><span>${icon('command')}</span> Context added. Signal extracted.</div><div><span class="tiny-dot"></span> Issue ready for the next step. <b>${icon('arrow-up-right')}</b></div></div><div class="art-status">INBOX ${icon('arrow-right')} CONTEXT ${icon('arrow-right')} ACTION <span>${icon('arrow-up-right')}</span></div></div>`;
}
function card(i, n) { const p = projects[i]; return `<a class="project-card" href="./projects/${slugs[i]}/">${art(i)}<div class="card-meta"><span>0${n + 1} / ${labels[i]}</span>${arrow}</div><h3>${esc(p.title)}</h3><p>${descriptions[i]}</p><div class="tags">${p.tags.slice(0, 3).map(t => `<span>${esc(t)}</span>`).join('')}</div><span class="case-link">Explore the project <span aria-hidden="true">${icon('arrow-right')}</span></span></a>`; }
const archive = [
  ['BirthdayWish', 'An interactive birthday tribute with riddles, photographs, and music.', 'WEB EXPERIENCE'],
  ['coffeebar', 'Loko’s Coffee Bar: menu, product, review, and contact pages.', 'WEB DESIGN'],
  ['sem3individual', 'A Cult.fit-inspired fitness website and interface study.', 'WEB DESIGN'],
  ['projectsem3', 'An early semester project exploring HTML, CSS, and JavaScript.', 'WEB FOUNDATIONS'],
  ['mindblend-Aiml', 'A notebook exploring COVID-19 data analysis and forecasting.', 'DATA EXPLORATION'],
  ['python-notes', 'Python notebooks, practice programs, and programming exercises.', 'LEARNING'],
  ['HTML-CLASS', 'Classroom experiments in page structure and HTML.', 'LEARNING'],
  ['css-CLASS', 'Styling experiments and classroom CSS practice.', 'LEARNING']
];
const home = `${head('Vraj Shah — AI & Python Engineer', me.bio, './')}${header()}
<main id="main">
<section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="tiny-dot"></span> AI / PYTHON ENGINEER</p><h1>Thoughtful code.<br>Useful <span class="serif">intelligence.</span></h1><p class="hero-intro">I’m Vraj. I build AI systems that connect the dots<br class="desktop"> between information and action.</p><div class="hero-actions"><a class="button" href="#work">Explore my work <span aria-hidden="true">${icon('arrow-down-right')}</span></a><a class="quiet-link" href="${me.github}" target="_blank" rel="noreferrer">GitHub ${arrow}</a></div><div class="hero-footnote"><span class="cross">${icon('plus')}</span> CURIOUS BY NATURE. INTENTIONAL BY DESIGN.</div></div>
<div class="orbital" aria-hidden="true"><div class="orbital-grid"></div><div class="orbit orbit-one"><i></i></div><div class="orbit orbit-two"><i></i></div><div class="orbit orbit-three"></div><div class="orbital-core"><svg viewBox="0 0 120 120"><path d="M30 32 59 88 89 32M43 59h34"/></svg></div><span class="orbit-label label-one">01 / RETRIEVE</span><span class="orbit-label label-two">02 / REASON</span><span class="orbit-label label-three">03 / ACT</span><span class="orbital-caption">INFORMATION ${icon('arrow-right')} INTELLIGENCE</span><span class="orbit-coordinate">23.0225° N<br>72.5714° E</span></div>
<div class="hero-bottom"><span>BASED IN AHMEDABAD, INDIA</span><a href="#work">SCROLL TO EXPLORE ${icon('arrow-down')}</a><span>BUILDING WITH CURIOSITY</span></div></section>
<div class="discipline-strip"><div class="wrap"><span>Python engineering</span><i>${icon('asterisk')}</i><span>Retrieval systems</span><i>${icon('asterisk')}</i><span>Intelligent agents</span><i>${icon('asterisk')}</i><span>Useful software</span></div></div>
<section class="section wrap" id="work"><div class="section-heading"><div><p class="eyebrow">01 / SELECTED WORK</p><h2>Ideas, made <span class="serif">real.</span></h2></div><p>Three explorations in making<br>complex systems genuinely useful.</p></div><div class="project-grid">${order.map(card).join('')}</div>
<details class="archive"><summary><span>Earlier experiments <small>THE LEARNING ARCHIVE / 08</small></span><span class="plus" aria-hidden="true">${icon('plus')}</span></summary><div class="archive-list">${archive.map(([name, desc, type]) => `<a href="${me.github}/${name}" target="_blank" rel="noreferrer"><span><strong>${name}</strong><small>${desc}</small></span><span class="archive-type">${type}</span>${arrow}</a>`).join('')}</div></details></section>
<section class="about-section" id="about"><div class="wrap about-grid"><div><p class="eyebrow">02 / THE PERSON BEHIND THE CODE</p><h2>Always asking<br><span class="serif">“what if?”</span></h2><div class="personal-stamp"><span>VS</span><div>VRAJ SHAH<small>ENGINEER & CURIOUS HUMAN</small></div><span aria-hidden="true">${icon('asterisk')}</span></div></div><div class="about-copy"><p class="large-copy">I like the moment a complicated problem becomes a useful tool.</p><p>${esc(me.bio)}</p><p>My journey began with web pages and Python notebooks. Today, I’m exploring how language models, retrieval pipelines, and reliable backends can work together to help people make sense of information.</p><p>I care about the pieces beneath the surface: clear abstractions, grounded answers, and workflows that know how to recover.</p><a class="quiet-link" href="${me.linkedin}" target="_blank" rel="noreferrer">More about me on LinkedIn ${arrow}</a></div></div></section>
<section class="section wrap experience-section" id="experience"><div class="section-heading"><div><p class="eyebrow">03 / THE JOURNEY</p><h2>A foundation.<br>A forward <span class="serif">direction.</span></h2></div><p>Learning by building.<br>Growing through real work.</p></div><div class="journey"><div class="journey-label">EXPERIENCE <span>${icon('arrow-down-right')}</span></div><div>${experience.map(e => `<article class="journey-entry"><div class="entry-heading"><div><h3>${esc(e.role)}</h3><p>${esc(e.company)}</p></div><span class="date">${esc(e.period)}</span></div><ul>${e.points.map(p => `<li>${esc(p)}</li>`).join('')}</ul></article>`).join('')}</div><div class="journey-label">EDUCATION <span>${icon('arrow-down-right')}</span></div><article class="journey-entry"><div class="entry-heading"><div><h3>${esc(education.degree)}</h3><p>${esc(education.institution)} · ${esc(education.location)}</p></div><span class="date">${esc(education.period)}</span></div></article></div></section>
<section class="section wrap toolkit"><div class="section-heading"><div><p class="eyebrow">04 / MY TOOLBOX</p><h2>The right tools.<br>The <span class="serif">right reasons.</span></h2></div><p>A practical toolkit for connecting<br>ideas to working systems.</p></div><div class="tool-grid">${Object.entries(skills).map(([area, list], i) => `<article><span class="tool-number">0${i + 1}</span><h3>${esc(area)}</h3><div class="tool-tags">${list.map(s => `<span>${esc(s)}</span>`).join('')}</div></article>`).join('')}</div></section>
<section class="contact-section" id="contact"><div class="wrap"><p class="eyebrow"><span class="tiny-dot"></span> 05 / MAKE A CONNECTION</p><h2>Something in mind?<br>Let’s make it <span class="serif">happen.</span></h2><div class="contact-bottom"><div><a class="contact-email" href="mailto:${me.email}">${me.email} ${arrow}</a><div class="copy-row"><button data-copy="${me.email}">Copy email ${icon('copy')}</button><span role="status" data-copy-status></span></div></div><div class="socials"><a href="${me.github}" target="_blank" rel="noreferrer">GitHub ${arrow}</a><a href="${me.linkedin}" target="_blank" rel="noreferrer">LinkedIn ${arrow}</a></div></div></div></section>
</main>${footer()}`;
await writeFile(new URL('index.html', out), home);
for (const [i, p] of projects.entries()) {
  const next = order[(order.indexOf(i) + 1) % order.length];
  const problems = [
    'An AI assistant needs more than a prompt. Documents, memory, tools, and model providers need to cooperate without becoming tightly coupled. This project explores those internals through a reusable framework.',
    'Understanding an unfamiliar repository means connecting source files, symbols, history, and intent. A simple semantic search can miss exact identifiers; a useful code assistant needs both lexical precision and contextual retrieval.',
    'Customer feedback is fragmented and repetitive. Turning an inbox into useful engineering input requires screening, context, duplicate checks, and reliable processing when individual steps fail.'
  ];
  const html = `${head(`${p.title} — Vraj Shah`, p.tagline, '../../')}${header('../../', true)}<main id="main" class="detail-main"><section class="wrap detail-hero"><a class="back-link" href="../../#work">${icon('arrow-left')} Back to selected work</a><p class="eyebrow">${labels[i]} / PROJECT NOTES</p><h1>${esc(p.title)}<span class="accent">.</span></h1><p class="detail-tagline">${esc(p.tagline)}</p><div class="detail-actions"><a class="button" href="${p.github}" target="_blank" rel="noreferrer">View source on GitHub ${arrow}</a><a class="quiet-link" href="${p.github}#readme" target="_blank" rel="noreferrer">Documentation ${arrow}</a></div><div class="detail-visual">${art(i)}<div class="visual-note"><span class="eyebrow">THE IDEA</span><h2>${esc(p.summary.split('. ')[0])}<span class="accent">.</span></h2><p>${descriptions[i]}</p></div></div><div class="metrics">${p.metrics.map(m => `<div><span>${esc(m.label)}</span><strong>${esc(m.value)}</strong></div>`).join('')}</div></section><section class="wrap detail-body"><aside><span class="eyebrow">ON THIS PAGE</span><a href="#overview">Overview</a><a href="#workflow">How it works</a><a href="#features">Inside the build</a><a href="#stack">Technology</a>${p.roadmap ? '<a href="#next">Next steps</a>' : ''}</aside><div class="detail-content"><section id="overview"><p class="eyebrow">01 / THE QUESTION</p><h2>Why build this?</h2><p>${problems[i]}</p><p>${esc(p.description)}</p></section><section id="workflow"><p class="eyebrow">02 / THE APPROACH</p><h2>From input to outcome.</h2><ol class="workflow">${p.steps.map((s, n) => `<li><span>0${n + 1}</span><h3>${esc(s)}</h3><span aria-hidden="true">${icon('arrow-down')}</span></li>`).join('')}</ol></section><section id="features"><p class="eyebrow">03 / INSIDE THE BUILD</p><h2>The details that matter.</h2><ul class="features">${p.features.map(f => `<li>${icon('arrow-up-right')}${esc(f)}</li>`).join('')}</ul></section><section id="stack"><p class="eyebrow">04 / TECHNOLOGY</p><h2>Built with.</h2><div class="tool-tags">${p.tags.map(t => `<span>${esc(t)}</span>`).join('')}</div></section>${p.roadmap ? `<section id="next"><p class="eyebrow">05 / LOOKING FORWARD · PLANNED</p><h2>The next chapter.</h2><p>${esc(p.roadmap)}</p></section>` : ''}<p class="source-note">Project notes based on the repository documentation. <a href="${p.github}#readme" target="_blank" rel="noreferrer">Explore the current README ${icon('arrow-up-right')}</a></p></div></section><a class="next-project wrap" href="../${slugs[next]}/"><span class="eyebrow">EXPLORE THE NEXT PROJECT</span><span>${esc(projects[next].title)} <span aria-hidden="true">${icon('arrow-up-right')}</span></span></a></main>${footer('../../')}`;
  await mkdir(new URL(`projects/${slugs[i]}/`, out), { recursive: true });
  await writeFile(new URL(`projects/${slugs[i]}/index.html`, out), html);
}
await writeFile(new URL('.nojekyll', out), '');
console.log('Built homepage and 3 project pages in dist/.');
